trigger:
  - master

pool:
  vmImage: ubuntu-20.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 14
  displayName: Install Node.js
- script: |
    set -o errexit -o pipefail
    npm ci
  displayName: Install dependencies
- script: |
    set -o errexit -o pipefail
    npm run format
  displayName: Run linter
- script: |
    set -o errexit -o pipefail
    npm run build
    npm run dist
  displayName: Build
- script: |
    set -o errexit -o pipefail
    npm run copyright -- --check
  displayName: Check copyright statements

